name: YouTube Video Uploader

on:
    schedule:
        - cron: "30 16 * * *" # Daily at 16:30
    workflow_dispatch: # Allows manual trigger

jobs:
    upload:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code from private repo
              uses: actions/checkout@v3
              with:
                  repository: chouaib-629/automatedPublicherYoutubeShorts # Replace with your private repo
                  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use the secret PAT for authentication

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run YouTube uploader
              env:
                  GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
                  YOUTUBE_CREDENTIALS: ${{ secrets.YOUTUBE_CREDENTIALS }}
              run: python youtube_uploader.py
