name: YouTube Video Uploader

on:
  schedule:
    - cron: '30 16 * * *' # Daily at 16:30
  workflow_dispatch: # Allows manual trigger

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create client_secrets.json and youtube_token.json from GitHub Secrets
        run: |
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" > ./client_secrets.json
          echo "${{ secrets.YOUTUBE_CREDENTIALS }}" > ./client_secrets_youtube.json

      - name: Run YouTube uploader
        run: python youtube_uploader.py